### ISSUE TITLE
Failed build after last update

### ISSUE THREAD

**Issue by poofleesni** [mhogomchungu/qCheckGMail#32]
CMakeFiles/qCheckGMail.dir/src/addaccount.cpp.o: In function `addaccount::useToken(bool)':
addaccount.cpp:(.text+0x99a): undefined reference to `gmailauthorization::gmailauthorization(QDialog*, std::function<void (QByteArray const&, std::function<void (QByteArray const&)>)>&, std::function<void ()>&&, std::function<void (QByteArray const&)>&&)'
collect2: error: ld returned 1 exit status
CMakeFiles/qCheckGMail.dir/build.make:485: recipe for target 'qCheckGMail' failed
make[2]: *** [qCheckGMail] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/qCheckGMail.dir/all' failed
make[1]: *** [CMakeFiles/qCheckGMail.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mhogomchungu** [comment]
It compiles file here with gcc 4.9.2 and clang 3.7.1

What version of what compiler are you using?

**Comment by mhogomchungu** [comment]
It also build fine on gcc 5.3.1 on ubuntu 16.04

**Comment by poofleesni** [comment]
gcc 6.1.1 (arch linux default). Still no good.

```textCMakeFiles/qCheckGMail.dir/src/addaccount.cpp.o:
 In function `addaccount::useToken(bool)':
addaccount.cpp:(.text+0x99a): undefined reference to `gmailauthorization::gmailauthorization(QDialog*, std::function<void (QByteArray const&, std::function<void (QByteArray const&)>)>&, std::function<void ()>&&, std::function<void (QByteArray const&)>&&)'
collect2: error: ld returned 1 exit status
CMakeFiles/qCheckGMail.dir/build.make:485: recipe for target 'qCheckGMail' failed
make[2]: *** [qCheckGMail] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/qCheckGMail.dir/all' failed
make[1]: *** [CMakeFiles/qCheckGMail.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2****```text

**Comment by mhogomchungu** [comment]
I can not see why its failing,could you try with clang? You maybe hitting a bug in gcc.

After you have installed clang(its C++ compiler),configure cmake to use it by first running the following command

```
export CXX=clang++
```

So the full command could be something like:

```
export CXX=clang++
cmake blablabla
make
make install
```

**Comment by poofleesni** [comment]
It fails with clang also:
```text
CMakeFiles/qCheckGMail.dir/src/addaccount.cpp.o: In function `addaccount::useToken(bool)':
/tmp/makepkg/qcheckgmail/src/qCheckGMail/src/addaccount.cpp:(.text+0x832): undefined reference to `gmailauthorization::gmailauthorization(QDialog*, std::function<void (QByteArray const&, std::function<void (QByteArray const&)>)>&, std::function<void ()>&&, std::function<void (QByteArray const&)>&&)'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/qCheckGMail.dir/build.make:485: recipe for target 'qCheckGMail' failed
make[2]: *** [qCheckGMail] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/qCheckGMail.dir/all' failed
make[1]: *** [CMakeFiles/qCheckGMail.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

It failed also with gcc 4.9 but message is something different, hope it helps:
```text
CMakeFiles/qCheckGMail.dir/src/addaccount.cpp.o: In function `addaccount::useToken(bool)':
addaccount.cpp:(.text+0xa66): undefined reference to `gmailauthorization::gmailauthorization(QDialog*, std::function<void (QByteArray const&, std::function<void (QByteArray const&)>)>&, std::function<void ()>&&, std::function<void (QByteArray const&)>&&)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libQt5Network.so: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libQt5Network.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
CMakeFiles/qCheckGMail.dir/build.make:485: recipe for target 'qCheckGMail' failed
make[2]: *** [qCheckGMail] Error 1
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/qCheckGMail.dir/all' failed
make[1]: *** [CMakeFiles/qCheckGMail.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mhogomchungu** [comment]
Can you try now with the latest git.

It was a build issue affecting KF5 build.

I dont have KF5 and hence i cant test this build right now.

The above explains why i missed this build error and why i also missed a crash you experience in the aouth support thread.

**Comment by poofleesni** [comment]
It's all good now, thanks.
